<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fu../source;../source.vcl;/usr/share/lazarus/2.0.12/packager/units/$(CPU_TARGET)-$(OS_TARGET);/usr/share/lazarus/2.0.12/components/lazutils/lib/$(CPU_TARGET)-$(OS_TARGET);/usr/share/lazarus/2.0.12/lcl/units/$(CPU_TARGET)-$(OS_TARGET);/usr/share/lazarus/2.0.12/lcl/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);.  -MDelphi -Scghi -CX -O4 -g -gl -gh -Xg -l -vewnhibq -dLCL -dLCL$(LCL_PLATFORM) PasLibVlcPlayer.pas"/>
</CONFIG>
